-- =====================================================================
-- NexCart BD — final-schema.sql  (BASE SCHEMA)
-- =====================================================================
-- Supabase SQL Editor-এ SBচেয়ে আগে এই ফাইলটা রান করুন, তারপর ক্রম অনুযায়ী:
--   1) final-schema.sql   ← (এই ফাইল)
--   2) migration-add-product-fields.sql
--   3) migration-nexcart-core.sql
--   4) migration-master-forms.sql
--   5) migration-fix-category.sql
--
-- সব statement idempotent (IF NOT EXISTS / DROP ... IF EXISTS) — নিরাপদে আবার রান করা যায়।
-- অ্যাপের আসল কোড (API রুট + পেজ) থেকে কলামগুলো মিলিয়ে বানানো হয়েছে।
-- লেখা (insert/update/delete) admin panel থেকে service_role key দিয়ে হয় → RLS bypass করে;
-- তাই শুধু "নিজের ডেটা পড়া"-র policy রাখা হয়েছে (storefront dashboard-এর জন্য)।
-- =====================================================================

-- ========== PROFILES (auth.users-এর সাথে যুক্ত; role: reseller | admin) ==========
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  phone text,
  full_name text,
  role text not null default 'reseller',      -- 'reseller' | 'admin'
  wallet_balance numeric default 0,
  created_at timestamptz default now()
);

-- ========== PRODUCTS (base; migration আরও কলাম যোগ করবে) ==========
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique,
  price numeric not null default 0,
  compare_at_price numeric,
  reseller_price numeric,
  commission_rate numeric default 0,          -- reseller commission %
  stock int default 0,
  category text,
  description text,
  image text,
  active boolean default true,
  created_at timestamptz default now()
);

-- ========== ORDERS (base; migration order_code/division/subtotal ইত্যাদি যোগ করবে) ==========
create table if not exists orders (
  id bigint generated by default as identity primary key,
  reseller_id uuid references auth.users(id) on delete set null,
  customer_name text,
  customer_phone text,
  product_id bigint references products(id),
  quantity int default 1,
  total_amount numeric default 0,
  payment_status text default 'pending',      -- pending | cod | verified | rejected
  status text default 'pending',              -- pending | confirmed | shipped | delivered | cancelled
  created_at timestamptz default now()
);

-- ========== OTP VERIFICATIONS (ফোন যাচাই) ==========
create table if not exists otp_verifications (
  id bigint generated by default as identity primary key,
  phone text not null,
  otp_code text not null,
  verified boolean default false,
  expires_at timestamptz,
  created_at timestamptz default now()
);

-- ========== SUBMISSIONS (payment/form সাবমিশন; form_id→master_forms FK migration-এ যোগ হবে) ==========
create table if not exists submissions (
  id bigint generated by default as identity primary key,
  form_id bigint,
  order_id bigint references orders(id) on delete set null,
  reseller_id uuid references auth.users(id) on delete set null,
  user_data jsonb,
  status text default 'pending',              -- pending | approved | rejected
  created_at timestamptz default now()
);

-- ========== COMMISSIONS (reseller আয়) ==========
create table if not exists commissions (
  id bigint generated by default as identity primary key,
  reseller_id uuid references auth.users(id) on delete cascade,
  order_id bigint references orders(id) on delete set null,
  amount numeric not null default 0,
  status text default 'earned',               -- earned | withdrawn
  created_at timestamptz default now()
);

-- ========== WITHDRAWS (reseller উত্তোলন অনুরোধ) ==========
create table if not exists withdraws (
  id bigint generated by default as identity primary key,
  reseller_id uuid references auth.users(id) on delete cascade,
  amount numeric not null,
  method text,
  account_number text,
  status text default 'pending',              -- pending | paid | rejected
  processed_at timestamptz,
  created_at timestamptz default now()
);

-- =====================================================================
-- ROW LEVEL SECURITY — "নিজের ডেটা পড়া" (writes হয় service_role দিয়ে)
-- (products-এর RLS migration-nexcart-core.sql-এ সেট হয়, তাই এখানে নয়)
-- =====================================================================

alter table profiles enable row level security;
drop policy if exists "read own profile" on profiles;
create policy "read own profile" on profiles for select using (id = auth.uid());

alter table orders enable row level security;
drop policy if exists "reseller reads own orders" on orders;
create policy "reseller reads own orders" on orders for select using (reseller_id = auth.uid());

alter table commissions enable row level security;
drop policy if exists "reseller reads own commissions" on commissions;
create policy "reseller reads own commissions" on commissions for select using (reseller_id = auth.uid());

alter table withdraws enable row level security;
drop policy if exists "reseller reads own withdraws" on withdraws;
create policy "reseller reads own withdraws" on withdraws for select using (reseller_id = auth.uid());

alter table submissions enable row level security;
drop policy if exists "reseller reads own submissions" on submissions;
create policy "reseller reads own submissions" on submissions for select using (reseller_id = auth.uid());

-- otp_verifications: শুধু service_role (কোনো public policy নেই)
alter table otp_verifications enable row level security;

-- =====================================================================
-- শেষ। এবার ধারাবাহিকভাবে migration ফাইলগুলো রান করুন।
-- =====================================================================
